maykin_demo/demo/urls.py
from .views import *
from django.urls import path

app_name = 'demo'

urlpatterns = [
    path('home', home, name="home-view"),
    path('register', register, name="register-view"),
    path('login', Userlogin, name="login-view"),
    path('edit', edit, name="edit-view"),
    path('delete/<int:pk>', deleteHotel, name="delete-view"),
    path('add', add, name="add"),
    path("<slug:slug>", hotelPage, name="hotel-view"),

]

maykin_demo/maykin_demo/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('demo.urls', namespace='demo')),
    path('', include("django.contrib.auth.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

maykin_demo/demo/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
# Create your models here.

class City (models.Model):

    cityCode = models.CharField(max_length=3)
    cityName = models.CharField(max_length=255)

    #useful for displaying the actual city names on the forms
    #rather than city object (1) etc
    def __str__(self):
        return self.cityName

class Hotel (models.Model):

    #slug field used so each hotel can have a page to be edited
    slug = models.SlugField(max_length=100, unique=True)
    city = models.ForeignKey(
        City, blank=True, on_delete=models.CASCADE)
    hotelCode = models.CharField(max_length=10)
    hotelName = models.CharField(max_length=255)

    def __str__(self):
        return self.hotelName
    
    #save the slug field
    def save(self, *args, **kwargs):
        value = self.hotelCode
        self.slug = slugify(value)
        super().save(*args, **kwargs)




class ExtendedUser(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    #on_delete=models.SET_NULL is used so that users are not deleted if the city
    #is. The user will be asked to select a new city however.
    city = models.ForeignKey(
        City, null=True, on_delete=models.SET_NULL)

maykin_demo/demo/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import ExtendedUser, Hotel
from django.forms import ModelForm

class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "password1", "password2"]

class ExtendedUserForm(ModelForm):

    class Meta:
        model = ExtendedUser
        fields = ['city']

class UpdateHotelForm(ModelForm):

    class Meta:
        model = Hotel
        fields = ['hotelName']

class NewHotelForm(ModelForm):

    class Meta:
        model = Hotel
        fields = ['hotelCode', 'hotelName']

maykin_demo/demo/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Hotel, City, ExtendedUser
from .forms import RegisterForm, ExtendedUserForm, NewHotelForm, UpdateHotelForm
from django.contrib.auth import login, authenticate
from .decorators import authenticated_user, unauthenticated_user
from django.http import Http404

# Create your views here.

def home(request):

    citySelected = None
    hotels = []
    #finds the relevant city
    for city in City.objects.filter():
        if city.cityName in request.GET:
            citySelected = city
            break
    
    #orders the hotels to be displayed
    if citySelected != None:
        hotels = Hotel.objects.filter(city=citySelected).order_by("hotelCode")


    context = {"empty": ((len(Hotel.objects.filter()) == 0) 
                         or (len(City.objects.filter()) == 0)),
               "cities": City.objects.filter().order_by("cityName"),
               "citySelected": citySelected,
               "hotels": hotels}
    
    return render(request, 'demo/home.html', context)



@unauthenticated_user
def register(response):
    if response.method == "POST":
        form = RegisterForm(response.POST)
        extended_form = ExtendedUserForm(response.POST)
        if form.is_valid() and extended_form.is_valid():
            user = form.save()
            #commit=False used to return the instance and not yet save to database
            extendedUserInstance = extended_form.save(commit=False)
            extendedUserInstance.user = user
            extendedUserInstance.save()
            return redirect("/login")
        else:
            pass
    else:
        form = RegisterForm()
        extended_form = ExtendedUserForm()
    context = {'form' : form, 'extended_form':extended_form}
    return render(response, "demo/register.html", context)


@unauthenticated_user
def Userlogin(response):

    failed = False
    if "failed" in response.GET:
        failed = True

    if response.method == "POST":
        username = response.POST.get('username')
        password = response.POST.get('password')

        user = authenticate(response, username=username, password=password)
        #the credentials are correct
        if user is not None:
            login(response, user)
            return redirect('/edit')
        else:
            return redirect("/login?failed")

    return render(response, "demo/login.html", {"failed":failed})


@authenticated_user
def edit(response):

    updated = False
    added = False
    deleted = False
    noCity = False
    form = None
    hotels = []

    #form for city has been submitted by user so extended user instance is updated
    if response.method == "POST":
        form = ExtendedUserForm(
            response.POST, instance=ExtendedUser.objects.get(user=response.user.id))
        if form.is_valid():
            form.save()
    else:

        if 'deleted' in response.GET:
            deleted = True 
        elif 'added' in response.GET:
            added = True
        elif 'updated' in response.GET:
            updated = True

        #the current user has no city so display the form
        if ExtendedUser.objects.get(user=response.user.id).city == None:
            form = ExtendedUserForm()
            noCity = True
        else:
            #all hotels in the current users city
            hotels = Hotel.objects.filter(city=ExtendedUser.objects.get(
                user=response.user.id).city).order_by("hotelCode")
    
        
    context = {"form": form, "noCity": noCity, "hotels": hotels,
                "deleted": deleted, "added": added, "updated": updated}
    return render(response, "demo/edit.html", context)

#view is actioned as a POST request from other views to delete hotel object
def deleteHotel(response, pk):
    try:
        hotel = Hotel.objects.get(id=pk)
    except:
        return redirect("/edit")
    
    if ExtendedUser.objects.get(user=response.user.id).city != hotel.city:
        return redirect("/edit")
        
    if response.method == "POST":
        hotel.delete()
        return redirect("/edit?deleted")
    
    else:
        return redirect("/edit")


@authenticated_user
def hotelPage(response, slug=None):

    hotel = None
    if slug is not None:
        try:
            hotel = Hotel.objects.get(slug=slug)
        except Hotel.DoesNotExist:
            raise Http404
        except Hotel.MultipleObjectsReturned:
           hotel = Hotel.objects.filter(slug=slug).first()
        except:
            raise Http404  
    
    #users assinged to different cities can only access those hotels
    if ExtendedUser.objects.get(user=response.user.id).city != hotel.city:
        return redirect("/home")
    else:
        if response.method == "POST":
            #pass in instance so that the record is updated rather than a new one created
            form = UpdateHotelForm(response.POST, instance=hotel)
            if form.is_valid():
                form.save()
                return redirect("/edit?updated")
        else:
            form = UpdateHotelForm()


    context = {"hotel": hotel, "form": form}

    return render(response, "demo/hotel.html", context)

@authenticated_user
def add(response):

    city = ExtendedUser.objects.get(user=response.user.id).city
    invalid = False
    exist = False

    if response.method == "POST":

        form = NewHotelForm(response.POST)
        if form.is_valid():
            #commit=false to change some more fields before saved
            hotel = form.save(commit=False)
            
            #the city code is the same as the beginning of the hotel code
            if city.cityCode.lower() == hotel.hotelCode.lower()[:len(city.cityCode)]:
                try:
                    #the rest of the string is numbers
                    int(hotel.hotelCode[len(city.cityCode):])
                    #no hotel exists with the same code
                    if len(Hotel.objects.filter(hotelCode=hotel.hotelCode.upper()))==0:
                        hotel.hotelCode = hotel.hotelCode.upper()
                        hotel.city = city
                        hotel.save()
                        return redirect("/edit?added")
                    else:
                        exist = True
                except ValueError:
                    invalid = True
            else:
                invalid = True
    else:
        form = NewHotelForm()
    
    context = {"form": form, "city": city, "invalid": invalid, "exist": exist}
    return render(response, "demo/add.html", context)
            

maykin_demo/demo/templates/demo/add.html
{% extends "demo/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <header><h1>Add new hotel in {{city}}</h1></header>
    <p>Please note that the hotel code must be be {{city.cityCode}} followed by integers eg {{city.cityCode}}01</p>
    <p>The hotel code is not case sensitive and will auto capitalise it</p>
    
    <form method="POST" class="form-group">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="btn btn-success">Add</button>
    </form>
    {% if invalid %}
        <br>
        <p>Invalid hotel code</p>
    {% elif exist %}
        <br>
        <p>Hotel code already exists, must be unique</p>
    {% endif %}
    
{% endblock %}

maykin_demo/demo/templates/demo/base.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <style>

            body {
                margin-top: 0;
            }

            /*side nav is the bar on the left hand side containing the cities.
            Displayed on the home page*/
            .side-nav {
                height:100%;
                width:175px;
                position: fixed;
                z-index:1;
                top:0;
                left:0;
                background-color:#aadae9;
                overflow-x:hidden;
                padding-top:20px;
            }

            .side-nav a {
                padding:5px 10px 5px 10px;
                text-decoration:none;
                font-size:28px;
                color: #000000;
                display:block;
            }

            .side-nav a:hover{
                color:#f1f1f1
            }

            .home-wrap{
                margin-left:175px;
                padding: 0px 10px;
            }

            .home{
                margin-top: 50px;
            }

            .no-style {
                list-style: none;
            }

            .all {
                text-align: center;
            }

            /*nav is the main nav bar in the top right containing the pages*/
            nav{
                display: flex;
                padding-right: 5%;
                justify-content: space-between;
                align-items: center;
                background-color:#aadae9;
            }
            .nav-links{
                flex: 1;
                text-align: right;
            }
            .nav-links ul li{
                list-style: none;
                display: inline-block;
                padding: 8px 12px;
                position: relative;
            }
            .nav-links ul li a{
                color: #000000;
                text-decoration: none;
                font-size: 13px;
            }

            .nav-links ul li a:hover{
                color: #ffffff
            }

            .edit-list {
                display: inline-block;
                width: 33%
                
            }

        </style>
    </head>
    <nav>
        <div class="nav-links">
            <i class="fa fa-times"></i>
            <ul>
                <li><a href="/home">HOME</a></li>
                {% if request.user.is_authenticated %}
                    <li><a href="/edit">EDIT</a></li>
                    <li><a href="/add">ADD</a></li>
                    <li><a href="/logout">LOGOUT</a></li>
                {% else %}
                    <li><a href="/register">REGISTER</a></li>
                    <li><a href="/login">LOGIN</a></li>
                {% endif %}
            </ul>
        </div>
        <i class="fa fa-bars" aria-hidden="true"></i>
    </nav>
    <body>
        <div class="all">
            {% block content %}
            {% endblock %}
        </div>
    </body>

</html>

maykin_demo/demo/templates/demo/edit.html
{% extends 'demo/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <header><h1>Edit</h1></header>


    {% if noCity %}

        <p>The city that you selected has been deleted. Please select a new city to manage</p>
        <form method="POST" class="form-group">
            {% csrf_token %}
            {{form|crispy}}
            <button type="submit" class="btn btn-success">Update</button>
        </form>
    {% else %}

        {% if deleted %}
            <p>Hotel deleted successfully</p>
        {% elif added %}
            <p>Hotel added successfully</p>
        {% elif updated %}
            <p>Hotel updated successfully</p>
        {% endif %}
        
        {% for hotel in hotels %}
            <div class="edit-list">
                <li class="no-style">{{hotel.hotelCode}} : {{hotel.hotelName}}</li>
                <a href="/{{hotel.hotelCode.lower}}">Update</a>
                <br>
                <br>
            </div>
        {% endfor %}
        
    {% endif %}

{% endblock %}

maykin_demo/demo/templates/demo/home.html
{% extends 'demo/base.html' %}

{% block content %}
    <div class="home-wrap">
        {% if empty %}
            <h2>No data has been imported</h2>
        {% else %}
        <!--The city pages are actually just the home page. If no city has been selected then
        the regular home page is displayed. Otherwise all the hotels are displayed in the selected city-->
            {% if citySelected != None %}
                <header><h1>{{citySelected.cityName}}</h1></header>
                <main class="home">
                    {% if hotels|length == 0 %}
                        <h2>Sorry we could not find any hotels in {{citySelected.cityName}}</h2>
                    {% else %}
                        {% for hotel in hotels %}
                            <li class="no-style">{{hotel.hotelCode}} : {{hotel.hotelName}}</li>
                            <br>
                        {% endfor %}
                    {% endif %}
                </main>
            {% else %}
                <header><h1>Welcome to hotel finder</h1></header>
                <main id="home">
                    <p>A program written by Owen Freeman as a test project for Maykin Media</p>
                    <p>Management command written to import data of hotels and cities over authenticated HTTP</p>
                    <p>Users can select these cities and view the respective hotels</p>
                    <p>Users can register for a certain city to add, update and remove hotels from that city</p>
                </main>
            {% endif %}


            <div class="side-nav">
                <br><br>
                {% for city in cities %}
                    <br>
                    <a href="/home?{{city.cityName}}">{{city.cityName}}</a>   
                {% endfor %} 
            </div>

        {% endif %}
    </div>
{% endblock %}

maykin_demo/demo/templates/demo/hotel.html
{% extends "demo/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <header><h1>{{hotel}}</h1></header>

    <form method="POST" class="form-group">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="btn btn-success">Update</button>
    </form>
    <br>
    <!--Method="post" ensures that the form is immediately submitted once
         this page is accessed.-->
    <form action="{% url 'demo:delete-view' hotel.pk %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Delete hotel">
    </form>
    
{% endblock %}

maykin_demo/demo/templates/demo/login.html
{% extends "demo/base.html" %}
{% load crispy_forms_tags %}

    

{% block content %}
	<h3 id="form-title">LOGIN</h3>		
	<form method="POST" action="">
		{% csrf_token %}	
		<input type="text" name="username" placeholder="Username..." class="form-control">		
		<input type="password" name="password" placeholder="Password..." class="form-control" >
		<input class="btn login_btn" type="submit" value="Login">	   			
	</form>
    {% if failed %}
        <p>Login failed, incorrect credentials</p>
    {% endif %}
    
{% endblock %}

maykin_demo/demo/templates/demo/register.html
{% extends "demo/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="register">
        <h1>Register</h1>
        <form method="POST" class="form-group">
            {% csrf_token %}
            {{form|crispy}}
            {{extended_form|crispy}}
            <button type="submit" class="btn btn-success">Register</button>
        </form>
    </div>
{% endblock %}